### ISSUE TITLE
Scrolling Animations needed

### ISSUE THREAD

**Issue by harshgoel05** [harshgoel05/hand-holding#21]
Need to add scrolling fade-up animation from [AOS](https://michalsnik.github.io/aos/) library.

**Comment by pexeixv** [comment]
Why AOS in particular? It can be done without using AOS, using CSS.

**Comment by Maxtasy** [comment]
Hi, I can do that. Please assign me.

**Comment by harshgoel05** [comment]
@pexeixv  Feel free to use CSS, need to make it animated with a professional look. AOS is a library check it out at https://michalsnik.github.io/aos/ as I used to do it with AOS, you know preference as its a lightweight and easy to use library.

**Comment by pexeixv** [comment]
Yes, I forked the repo and tried working AOS. It's not getting animated I have no idea why. I'm suspecting Bootstrap is interfering with it.

**Comment by Maxtasy** [comment]
I got it to work before you added the loader animation. Doesn't seem to work now.

**Comment by harshgoel05** [comment]
Yeah! This is an issue, happening due to the loader. Can we fix it? anyhow, we might use some other library/method to add loader animation atlast.

**Comment by pexeixv** [comment]
Seems like you'll have to get rid of the loader animation. That's just my opinion.
