### ISSUE TITLE
Fix :  The services section must come center aligned

### ISSUE THREAD

**Issue by harshgoel05** [harshgoel05/hand-holding#4]
The services section must come center-aligned vertically to the screen on index.html. The blue background should cover the whole screen and no white part should be visible.

**Comment by adithyakam** [comment]
hI,
CAN I WORK ON THIS

**Comment by Adityachaturvedi2906** [comment]
Please assign me this work @harshgoel05,  I will this out!

**Comment by shradhaagarwal01** [comment]
hey @harshgoel05 can you give more explanation ?

**Comment by harshgoel05** [comment]
Assigned to @adithyakam , the website is live on https://handholdingsolution.com on the homepage look on the services section. When the user scrolls to the services section, the blue background to the section must cover the whole background.

**Comment by harshgoel05** [comment]
Hey @Adityachaturvedi2906 are you working on it? Please let me know if you are.

**Comment by Adityachaturvedi2906** [comment]
> Hey @Adityachaturvedi2906 are you working on it? Please let me know if you are. 

Hello,
Yes the work is in progress.
