### ISSUE TITLE
Improvement:  Add AOS animations on scroll

### ISSUE THREAD

**Issue by harshgoel05** [harshgoel05/hand-holding#5]
### **On scroll animations to cards and sections needed**

Please checkout [AOS Library](https://michalsnik.github.io/aos/) which provides awesome on scroll animations.
Need to add it to home screen and services screen.

**Comment by Divyanshwick** [comment]
Hey, I would like to work on this issue

**Comment by harshgoel05** [comment]
Hey @Divyanshwick ! You are all set. You can work on this 🚀

**Comment by harshgoel05** [comment]
@Malhar37 #8

**Comment by Divyanshwick** [comment]
@harshgoel05  what kind of behaviour is this ?? I have made the pr please review it, It looks much better than @Malhar37
