### ISSUE TITLE
Rename all images and add alt tags

### ISSUE THREAD

**Issue by harshgoel05** [harshgoel05/hand-holding#6]
The images are not properly named. 
To do:  Rename the images properly in snake case for example web_development_icon

**Comment by UshasriMavuri1999** [comment]
can you please assign this to me?

**Comment by Priya19999** [comment]
Can I please work on this issue?

**Comment by ShobhitRathi** [comment]
hey cool, im also working on this

**Comment by harshgoel05** [comment]
Hey @UshasriMavuri1999 , assigning the task to you! 🚀

**Comment by Ramandeep9898** [comment]
hlo sir, i would like to do this :>
it will be really kind of u if u can let me do this too :)

**Comment by ShobhitRathi** [comment]
@harshgoel05 checkout my PR and tell me if you still need any changes

**Comment by harshgoel05** [comment]
Hey! @ShobhitRathi it looks great but it was already assigned to @UshasriMavuri1999, will check her PR and if that's not great. Will merge yours.

**Comment by ShobhitRathi** [comment]
@harshgoel05 cool you can merge it anytime you want

**Comment by harshgoel05** [comment]
Closing this #14 #19
