### ISSUE TITLE
beautify README.md

### ISSUE THREAD

**Issue by harshgoel05** [harshgoel05/hand-holding#9]
Need to add a proper README for the website which includes tech stack, screenshots, and description.

**Comment by Priya19999** [comment]
Can I please work on this?

**Comment by harshgoel05** [comment]
@Priya19999  sure! Go ahead!

**Comment by abnersouza** [comment]
Hi @harshgoel05 I've created a pull request for this issue [#20 ](https://github.com/harshgoel05/hand-holding/pull/20)
